spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotresvib
    driver-class-name: org.postgresql.Driver
    username: hotresvib_user
    password: "hotresvib_pass"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration/demo

security:
  jwt:
    secret: "0123456789abcdef0123456789abcdef"

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

---
# Demo profile for local H2-based runs
spring:
  config:
    activate:
      on-profile: demo
  datasource:
    url: jdbc:h2:mem:hotresvib;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration/demo
